### ISSUE TITLE
Cannot read property 'preferNative' of undefined

### ISSUE THREAD

**Issue by niltz** [auth0-community/ember-simple-auth-auth0#132]
Steps to reproduce:

```
ember new my-app --yarn
ember install ember-simple-auth-auth0
ember s

Cannot read property 'preferNative' of undefined
```

```
ERROR Summary:

  - broccoliBuilderErrorStack: [undefined]
  - codeFrame: [undefined]
  - errorMessage: Cannot read property 'preferNative' of undefined
  - errorType: [undefined]
  - location:
    - column: [undefined]
    - file: [undefined]
    - line: [undefined]
  - message: Cannot read property 'preferNative' of undefined
  - name: TypeError
  - nodeAnnotation: [undefined]
  - nodeName: [undefined]
  - originalErrorMessage: [undefined]
  - stack: TypeError: Cannot read property 'preferNative' of undefined
    at Class.treeForVendor (/Users/jeff/Code/my-app/node_modules/ember-fetch/index.js:109:43)
    at Class._treeFor (/Users/jeff/Code/my-app/node_modules/ember-cli/lib/models/addon.js:583:33)
    at Class.treeFor (/Users/jeff/Code/my-app/node_modules/ember-cli/lib/models/addon.js:543:21)
    at addons.reduce (/Users/jeff/Code/my-app/node_modules/ember-cli/lib/models/addon.js:416:26)
    at Array.reduce (<anonymous>)
    at Class.eachAddonInvoke (/Users/jeff/Code/my-app/node_modules/ember-cli/lib/models/addon.js:413:24)
    at Class.treeFor (/Users/jeff/Code/my-app/node_modules/ember-cli/lib/models/addon.js:542:22)
    at addons.reduce (/Users/jeff/Code/my-app/node_modules/ember-cli/lib/models/addon.js:416:26)
    at Array.reduce (<anonymous>)
    at Class.eachAddonInvoke (/Users/jeff/Code/my-app/node_modules/ember-cli/lib/models/addon.js:413:24)
```

**Comment by niltz** [comment]
I have node v10.7.0

Here is a zip with my package.json and yarn.lock file:

[Archive.zip](https://github.com/auth0-community/ember-simple-auth-auth0/files/2242268/Archive.zip)

**Comment by XaserAcheron** [comment]
Would you mind trying to install the `develop` branch (e.g. `yarn install https://github.com/auth0-community/ember-simple-auth-auth0.git#develop`)? The latest release has at least one known issue with building (#129) which is fixed for the next release, so it'd be good to confirm there isn't anything else going awry.

**Comment by niltz** [comment]
That seems to fix it. Thanks!

**Comment by XaserAcheron** [comment]
No problem -- thanks for testing!

Means I really ought to just release 4.1.0 -- I'll postpone the silentAuth stuff until the next version, since this build business is mucking with things.

**Comment by XaserAcheron** [comment]
Tagged this with [duplicate] since it's basically #129 -- not to say this wasn't valuable or anything.
