### ISSUE TITLE
Error: Cannot find module 'broccoli-webpack'

### ISSUE THREAD

**Issue by roschaefer** [auth0-community/ember-simple-auth-auth0#79]
We're on the `development` branch because we need 23e525a7d619798a7953ab59c70762c49e5a2b9b which is not released yet.

@lbmorales pointed out that with a clean install of [our ember app](https://github.com/roschaefer/rundfunk-mitbestimmen) you see this error if you do `ember --version`:

```
Cannot find module 'broccoli-webpack'
Error: Cannot find module 'broccoli-webpack'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/robert/Development/Rails/rundfunk-mitbestimmen/frontend/node_modules/ember-simple-auth-auth0/index.js:7:17)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Function.Addon.lookup (/home/robert/Development/Rails/rundfunk-mitbestimmen/frontend/node_modules/ember-cli/lib/models/addon.js:1634:19)
    at graph.each.e (/home/robert/Development/Rails/rundfunk-mitbestimmen/frontend/node_modules/ember-cli/lib/models/addons-factory.js:54:38)
    at Vertices.each (/home/robert/Development/Rails/rundfunk-mitbestimmen/frontend/node_modules/dag-map/dag-map.umd.js:197:13)
    at Vertices.walk (/home/robert/Development/Rails/rundfunk-mitbestimmen/frontend/node_modules/dag-map/dag-map.umd.js:125:14)
    at DAG.each (/home/robert/Development/Rails/rundfunk-mitbestimmen/frontend/node_modules/dag-map/dag-map.umd.js:68:24)
    at AddonsFactory.initializeAddons (/home/robert/Development/Rails/rundfunk-mitbestimmen/frontend/node_modules/ember-cli/lib/models/addons-factory.js:45:11)
    at Project.initializeAddons (/home/robert/Development/Rails/rundfunk-mitbestimmen/frontend/node_modules/ember-cli/lib/models/project.js:418:38)
    at Project.eachAddonCommand (/home/robert/Development/Rails/rundfunk-mitbestimmen/frontend/node_modules/ember-cli/lib/models/project.js:480:12)
    at module.exports (/home/robert/Development/Rails/rundfunk-mitbestimmen/frontend/node_modules/ember-cli/lib/cli/lookup-command.js:33:13)
    at RSVP.hash.then.environment (/home/robert/Development/Rails/rundfunk-mitbestimmen/frontend/node_modules/ember-cli/lib/cli/cli.js:97:28)
    at tryCatch (/home/robert/Development/Rails/rundfunk-mitbestimmen/frontend/node_modules/rsvp/dist/rsvp.js:525:12)
    at invokeCallback (/home/robert/Development/Rails/rundfunk-mitbestimmen/frontend/node_modules/rsvp/dist/rsvp.js:538:13)
    at /home/robert/Development/Rails/rundfunk-mitbestimmen/frontend/node_modules/rsvp/dist/rsvp.js:606:14
    at flush (/home/robert/Development/Rails/rundfunk-mitbestimmen/frontend/node_modules/rsvp/dist/rsvp.js:2415:5)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

And that's because `broccoli-webpack` is a development dependency since: 1a9bbb1d0701673c1795cf9c5dce51f213116e03

**Comment by XaserAcheron** [comment]
Just opened a PR for this -- it's the usual "oops": `broccoli-webpack` ought to have gone in `dependencies`, not `devDependencies`.
